environment:
  matrix:
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.14"
#      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

install:
  # use the version of python to test, instead of
  # the default (currently 2.7)
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build_script:
  - "pip install numpy h5py wheel"
  - "python setup.py build"

test_script:
  - "python setup.py nosetests"

after_test:
  - "python setup.py bdist_wheel"
